### ISSUE TITLE
I can not cargo.

### ISSUE THREAD

**Issue by franklili3** [keorn/parity-spec#1]
When I have done precious steps, and run"cargo run --geth-spec.json", the error appears, 
"error[E0554]: #[feature] may not be used on the stable release channel
 --> C:\Users\franknbw10\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_codegen-0.8.16\src\lib.rs:5:43
  |
5 | #![cfg_attr(not(feature = "with-syntex"), feature(rustc_private, plugin))]
  |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error: Could not compile `serde_codegen`.". How can I do?

**Comment by keorn** [comment]
You are trying to run with stable Rust compiler, nightly is required.
As per third command in the instructions run: `rustup default nightly` before trying to `cargo run`.
