### ISSUE TITLE
error: An unknown error occurred

### ISSUE THREAD

**Issue by avatar-lavventura** [keorn/parity-spec#11]
I am facing with the following error. What may be the reason this happens?

```
*[master][~/parity-spec]$ cargo run -- example-geth.json
error: An unknown error occurred

To learn more, run the command again with --verbose.
```

**Comment by 5chdn** [comment]
> To learn more, run the command again with --verbose.

Could you do that?

**Comment by 5chdn** [comment]
It turns out @avatar-lavventura had no rustc insalled on his system.
