### ISSUE TITLE
Does this add builtin contracts?

### ISSUE THREAD

**Issue by 5chdn** [keorn/parity-spec#12]
I had a hard time to figure out why parity wouldn't connect into a geth private network until I found this ticket https://github.com/paritytech/parity/issues/2794

I was helping @avatar-lavventura and he used _this_ tool to generate the parity genesis from his geth genesis as documented here https://github.com/avatar-lavventura/someCode/issues/2

Does `parity-spec` add builtin contracts?

**Comment by keorn** [comment]
Yes, it does. But only if the implicit builtin address balances are in the Geth spec (see examples). Can make it add them always, but not sure what the implicit balance is (I dont think 0 works).
