### ISSUE TITLE
unknown crate type: `proc-macro`

### ISSUE THREAD

**Issue by immartian** [keorn/parity-spec#2]
after running > cargo run --verbose geth.json , I received: 

```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name _ --print=file-names --crate-type bin --crate-type proc-macro --crate-type rlib --target x86_64-unknown-linux-gnu` (exit code: 101)
--- stderr
error: unknown crate type: `proc-macro`
```

Any clues?

**Comment by keorn** [comment]
Are you sure you are running `cargo run -- geth-spec.json` as indicated in the README? Notice the `--` missing in your post.

**Comment by immartian** [comment]
yes, it's actually started from `run --`, the `--verbose` is only for showing details. 
Anyway, it's been solved by installing nightly of rustc, not sure what's the exact reason though.
