### ISSUE TITLE
geth-spec.json and parity-spec.json produce different genesis blocks

### ISSUE THREAD

**Issue by vrogojin** [keorn/parity-spec#21]
I tried to use your spec.json examples to initiate private networks on geth and parity. First of all, parity does not accept your example-parity.json. It complains "Spec json is invalid: missing field `gasLimitBoundDivisor` at line 19 column 3". I moved gasLimitBoundDivisor to general params section. Then, I tried to launch geth with example-geth.json and parity with example-parity.json. However, parity and geth produce genesis blocks with different hashes "TRACE sync  Peer 0 genesis hash mismatch (ours: 536c…5b6c, theirs: d4e5…8fa3)". Of course, I get also mismatches between geth and parity genesis blocks if using your app to convert from example-geth.json.

**Comment by vrogojin** [comment]
Addition: I use
- Ubuntu 14.04
- Parity v1.8.9-stable
- Geth v1.8.1-stable

**Comment by keorn** [comment]
Closed by #22
