### ISSUE TITLE
Figure out new default transition blocks

### ISSUE THREAD

**Issue by keorn** [keorn/parity-spec#6]
Seems like the defaults were changed in Geth for:
```
        "homesteadBlock": "0x00",
        "EIP150Block": "0x00",
        "EIP155Block": "0x00",
        "EIP158Block": "0x00"
```

**Comment by rphmeier** [comment]
My mistake from earlier; fork config is done through "config" field of genesis.json and the capitalization for EIP fields was wrong.

```json
{
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0
}
```

And maybe a `chainId` field is necessary too in the presence of an `eip155` fork.

**Comment by keorn** [comment]
Yes, its correct in the translator: https://github.com/keorn/parity-spec/blob/master/src/main.rs#L23
Just need to adjust the numbers

**Comment by keorn** [comment]
Chain id is required. If not present in spec, then there is a prompt asking for it.
Disabled all transitions by default, if having issues please refer to the Ropsten spec in the README.
